FROM mcr.microsoft.com/devcontainers/python:3.11-bookworm

COPY --from=ghcr.io/astral-sh/uv:0.11.8 /uv /uvx /bin/

ENV UV_PROJECT_ENVIRONMENT=.venv
ENV UV_LINK_MODE=copy
ENV UV_COMPILE_BYTECODE=1

USER vscode
